name: zedor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1



environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  introduction_screen: ^3.0.2
  flutter_launcher_icons: ^0.10.0
  hive: ^2.2.3
  scoped_model: ^2.0.0
  path_provider: ^2.0.3
  rxdart: ^0.27.3
  flutter_screenutil: ^5.5.4
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_local_notifications: ^13.0.0
  socket_io_client: ^2.0.1
  http: ^0.13.5
  get: ^4.6.1
  flutter_switch: ^0.3.2
  otp_text_field: ^1.1.3
  permission_handler: ^10.2.0
  web_socket_channel: ^2.1.0
  contacts_service: ^0.6.3
  sqflite: ^2.0.1
  path: ^1.8.0
  encrypt: 5.0.0
  shared_preferences: ^2.0.0
  flutter_overlay_window: ^0.4.1
  app_launcher: ^1.0.0
  scaffold_gradient_background: ^1.0.3+1


# Salsa20 encryptions use

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "images/zedor_logo.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - Language/

